name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ml-api-demo:$(date +%s)

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: |
        docker tag ml-api-demo:$(date +%s) ${{ secrets.DOCKER_USERNAME }}/ml-api-demo:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ml-api-demo:latest
